[app]
address = "0.0.0.0:9000"

[db]
host = "${DB_HOST}"
port = 5432
user = "${DB_USER}"
password = "${DB_PASSWORD}"
database = "${DB_NAME}"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
params = ""


[api]
enable = true
