x-db-credentials: &db-credentials
  POSTGRES_USER: &db-user listmonk
  POSTGRES_PASSWORD: &db-password listmonk
  POSTGRES_DB: &db-name listmonk

services:
  app:
    image: ghcr.io/knadh/listmonk:latest
    container_name: listmonk_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - listmonk
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    command: >
      sh -c "/listmonk/listmonk --install --idempotent --yes --config /listmonk/config.toml &&
             /listmonk/listmonk --upgrade --yes --config /listmonk/config.toml &&
             /listmonk/listmonk --config /listmonk/config.toml"
    environment:
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__user: *db-user
      LISTMONK_db__password: *db-password
      LISTMONK_db__database: *db-name
      LISTMONK_db__host: db
      LISTMONK_db__port: 5432
      LISTMONK_db__ssl_mode: disable
      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s



      # SMTP / MailHog
      LISTMONK_smtp__host: mailhog
      LISTMONK_smtp__port: 1025
      LISTMONK_smtp__from_email: "noreply@example.com"
      LISTMONK_smtp__username: ""
      LISTMONK_smtp__password: ""
      LISTMONK_smtp__encryption: none

    volumes:
      - ./uploads:/listmonk/uploads:rw
      - ./config.toml:/listmonk/config.toml:rw

  db:
    image: postgres:17-alpine
    container_name: listmonk_db
    restart: unless-stopped
    networks:
      - listmonk
    environment:
      <<: *db-credentials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - listmonk

  fastapi:
    build: ./fastapi
    container_name: listmonk_fastapi
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    networks:
      - listmonk
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://listmonk:listmonk@db:5432/listmonk"

networks:
  listmonk:

volumes:
  listmonk-data:
