services:
  - type: web
    name: listmonk
    plan: starter
    image:
      url: ghcr.io/knadh/listmonk:latest
    envVars:
      - key: LISTMONK_db__user
        value: twosteps_db_user
      - key: LISTMONK_db__password
        value: kDCh4C4LsI2Y438GPc71S5bO7Sr3rdda
      - key: LISTMONK_db__database
        value: twosteps_db
      - key: LISTMONK_db__host
        value: dpg-d3n5bkj3fgac73abqdog-a
      - key: LISTMONK_db__port
        value: 5432
      - key: LISTMONK_db__ssl_mode
        value: disable
