[app]
address = "0.0.0.0:9000"

[db]
host = "${LISTMONK_db__host}"
port = "${LISTMONK_db__port}"
user = "${LISTMONK_db__user}"
password = "${LISTMONK_db__password}"
database = "${LISTMONK_db__database}"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
params = ""


[api]
enable = true
